import { describe, expect, test } from "bun:test";
import {
  collectMatchedSessions,
  includesSessionId,
  mapFleetPRs,
  matchesRedispatchSession,
  matchesSession,
  type FleetPullRef,
  type SessionRef,
} from "./session-matching.ts";

describe("session matching", () => {
  const sessions: SessionRef[] = [
    { taskId: "task-a", sessionId: "abc123" },
    { taskId: "task-b", sessionId: "abc12345" },
    { taskId: "task-c", sessionId: "xyz999" },
  ];

  test("includesSessionId uses boundary-aware matching", () => {
    expect(includesSessionId("jules/abc123", "abc123")).toBe(true);
    expect(includesSessionId("jules/abc12345", "abc123")).toBe(false);
    expect(includesSessionId("session abc123 done", "abc123")).toBe(true);
    expect(includesSessionId("session-abc12345", "abc123")).toBe(false);
  });

  test("collectMatchedSessions returns only exact session matches", () => {
    const pr: FleetPullRef = {
      number: 42,
      head: { ref: "jules/abc12345", repo: { full_name: "owner/repo" } },
      body: "Generated by session abc12345",
    };

    const matched = collectMatchedSessions(pr, sessions, {
      expectedRepoFullName: "owner/repo",
      allowBodyMatch: true,
    });
    expect(matched).toHaveLength(1);
    expect(matched[0]?.taskId).toBe("task-b");
  });

  test("mapFleetPRs ignores ambiguous PRs", () => {
    const pulls: FleetPullRef[] = [
      {
        number: 10,
        head: { ref: "jules/abc123", repo: { full_name: "owner/repo" } },
        body: "session abc123",
      },
      {
        number: 11,
        head: { ref: "jules/ambiguous", repo: { full_name: "owner/repo" } },
        body: "mentions abc123 and xyz999 in same body",
      },
    ];

    const map = mapFleetPRs(pulls, sessions, {
      expectedRepoFullName: "owner/repo",
      allowBodyMatch: true,
    });
    expect(map.size).toBe(1);
    expect(map.get("task-a")?.number).toBe(10);
    expect(map.get("task-c")).toBeUndefined();
  });

  test("mapFleetPRs fails closed when two PRs map to the same task", () => {
    const pulls: FleetPullRef[] = [
      {
        number: 21,
        head: { ref: "jules/abc123", repo: { full_name: "owner/repo" } },
        body: null,
      },
      {
        number: 22,
        head: { ref: "hotfix/abc123", repo: { full_name: "owner/repo" } },
        body: null,
      },
    ];

    expect(() =>
      mapFleetPRs(pulls, sessions, {
        expectedRepoFullName: "owner/repo",
      })
    ).toThrow(/Ambiguous mapping/);
  });

  test("matchesSession rejects forked PRs even when session id is present", () => {
    const pr: FleetPullRef = {
      number: 44,
      head: { ref: "jules/abc123", repo: { full_name: "attacker/fork" } },
      body: "abc123",
    };

    expect(
      matchesSession(pr, "abc123", {
        expectedRepoFullName: "owner/repo",
        allowBodyMatch: true,
      })
    ).toBe(false);
  });

  test("matchesRedispatchSession enforces author and not-before constraints", () => {
    const now = Date.now();
    const pr: FleetPullRef = {
      number: 52,
      head: { ref: "jules/abc123", repo: { full_name: "owner/repo" } },
      body: "session abc123",
      user: { login: "jules[bot]" },
      created_at: new Date(now + 1000).toISOString(),
    };

    expect(
      matchesRedispatchSession(pr, "abc123", {
        expectedRepoFullName: "owner/repo",
        expectedAuthorLogin: "jules[bot]",
        notBeforeEpochMs: now,
      })
    ).toBe(true);

    expect(
      matchesRedispatchSession(pr, "abc123", {
        expectedRepoFullName: "owner/repo",
        expectedAuthorLogin: "someone-else",
        notBeforeEpochMs: now,
      })
    ).toBe(false);

    expect(
      matchesRedispatchSession(
        { ...pr, created_at: new Date(now - 1000).toISOString() },
        "abc123",
        {
          expectedRepoFullName: "owner/repo",
          expectedAuthorLogin: "jules[bot]",
          notBeforeEpochMs: now,
        }
      )
    ).toBe(false);

    expect(
      matchesRedispatchSession(
        { ...pr, created_at: null },
        "abc123",
        {
          expectedRepoFullName: "owner/repo",
          expectedAuthorLogin: "jules[bot]",
          notBeforeEpochMs: now,
        }
      )
    ).toBe(false);
  });

  test("matchesRedispatchSession accepts PRs created in same second as redispatch", () => {
    const baseMs = 1_700_000_000_250;
    const sameSecondCreatedAt = new Date(1_700_000_000_000).toISOString();
    const pr: FleetPullRef = {
      number: 54,
      head: { ref: "jules/abc123", repo: { full_name: "owner/repo" } },
      body: "session abc123",
      user: { login: "jules[bot]" },
      created_at: sameSecondCreatedAt,
    };

    expect(
      matchesRedispatchSession(pr, "abc123", {
        expectedRepoFullName: "owner/repo",
        expectedAuthorLogin: "jules[bot]",
        notBeforeEpochMs: baseMs,
      })
    ).toBe(true);
  });

  test("matchesRedispatchSession rejects body-only session matches", () => {
    const now = Date.now();
    const pr: FleetPullRef = {
      number: 53,
      head: { ref: "jules/no-session-token", repo: { full_name: "owner/repo" } },
      body: "redispatch for session abc123",
      user: { login: "jules[bot]" },
      created_at: new Date(now + 1000).toISOString(),
    };

    expect(
      matchesRedispatchSession(pr, "abc123", {
        expectedRepoFullName: "owner/repo",
        expectedAuthorLogin: "jules[bot]",
        notBeforeEpochMs: now,
      })
    ).toBe(false);
  });
});
